env_name: "PointMassObstacle-v0"
env_settings:
  params:
    _target_: rl_utils.envs.pointmass.PointMassObstacleParams
    start_state_noise: 0.1
    dt: 0.05
    ep_horizon: 50
    start_idx: 0
    square_obstacles:
      - _target_: rl_utils.envs.pointmass.SquareObstacle
        xy: [0.5, 0.5]
        width: 0.44
        height: 0.1
        rot_deg: -45.0
  set_eval: False

